##########################
## SECTION: Diagnostics 
##########################
GET http://localhost:8020/api/diagnostic/version

#### 
GET http://localhost:8020/api/diagnostic/testing


##########################
## SECTION: Definitions
##########################
GET http://localhost:8020/api/definitions/states


##########################
## SECTION: Entity
##########################

GET http://localhost:8020/api/individual?id=1

#####
PATCH http://localhost:8020/api/individual
Content-Type: "application/json" 

{
    "entityId": 1,
    "entityType": 1,
    "entityName": "mr. beanie 123",
    "note": "something here"
}

#####
GET http://localhost:8020/api/entity/search?entityId=1

#####
GET http://localhost:8020/api/entity/search?entityName=mr

#####
GET http://localhost:8020/api/entity/search?

##########################
## SECTION: Authentication
##########################
GET http://localhost:8020/auth/google/register

#######
GET http://localhost:8020/auth/google/verify

#######
GET http://localhost:8020/auth/google/refresh

#######
GET http://localhost:8020/auth/google/userDetails

#######
GET http://localhost:8020/mail/send


##########################
## SECTION: Cron 
##########################
GET http://localhost:8020/cron/start

####
GET http://localhost:8020/cron/pause

####
GET http://localhost:8020/cron/resume

