#### 
GET http://localhost:8020/api/diagnostic/version

#####
GET http://localhost:8020/api/individual/1

#####
PATCH http://localhost:8020/api/individual
Content-Type: "application/json" 

{
    "entityId": 1,
    "entityType": 1,
    "entityName": "mr. beanie",
    "note": "something here"
}

#####
GET http://localhost:8020/api/definitions/states
Content-Type: "application/json" 

{
    "entityName": "testing 123456"
}